import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const TRANSLATIONS = {
  en: {
    // Navigation
    home: "Home",
    about: "About",
    guide: "Guide",
    contact: "Contact",
    dashboard: "Dashboard",
    login: "Login",
    logout: "Logout",
    profile: "Profile",
    road_safety: "Safety Guidelines",
    vision_mission: "Vision & Mission",
    language_label: "LANGUAGE",
    navigation: "NAVIGATION",

    // Home Page
    hero_title: "Seconds Save Lives.",
    hero_sub: "RastaSaathi isn't just an app—it's a mission-critical infrastructure that bridges the gap between road accidents and high-precision medical care.",
    view_guide: "View Emergency Guide",
    vision: "Our Vision",
    national_initiative: "NATIONAL ROAD SAFETY INITIATIVE",
    precision_eng: "PRECISION ENGINEERING",
    impact_title: "Empowering Every Citizen",
    results_title: "Engineered for Results.",
    journey_title: "3 Steps to Safety",
    journey_sub: "A precision-engineered orchestration of technology and medical expertise.",
    step1_title: "Trigger SOS",
    step1_desc: "Tap the emergency button to start the protocol. We capture precise GPS coordinates.",
    step2_title: "AI Assessment",
    step2_desc: "Our medical engine identifies injury severity and hospital needs using real-time inputs.",
    step3_title: "Rescue Commences",
    step3_desc: "The nearest hospital is alerted, emergency contacts are notified, and navigation starts.",
    join_national_mission: "Join the National Mission",
    become_responder: "Become a Responder",

    // Dashboard
    secure_terminal: "SECURE EMERGENCY TERMINAL",
    ready_dispatch: "Ready for Dispatch.",
    trigger_sub: "Trigger the SOS for instant geospatial triage and emergency alerts.",
    sos_active: "SOS ACTIVE",
    geospatial_grid: "Geospatial Grid",
    system_status: "System Status",
    sync_grid: "Synchronizing Grid...",
    dispatched_alerts: "Dispatched Alerts.",
    target_center: "Target Center",
    calculating: "Calculating...",
    ai_medic: "AI Medic",
    emergency_guidance: "Emergency guidance...",
    medic_welcome: "RastaSaathi AI Medic activated. I am monitoring your grid. Trigger SOS for immediate medical coordination.",
    initiating_protocol: "INITIATING EMERGENCY PROTOCOL: Acquiring GPS telemetry...",
    gps_acquired: "📍 GPS COORDINATES ACQUIRED: ",
    sync_national: "Synchronizing with national medical grid...",
    sos_success: "✅ SOS DISPATCHED SUCCESSFULLY!",
    contacts_notified: "📲 WhatsApp alerts sent to emergency contacts.",
    nearest_hospital: "🏥 NEAREST HOSPITAL: ",
    eta: "⏳ ETA: ",
    no_hospitals: "⚠️ ALERT: SOS triggered, but no hospitals found in immediate range.",
    ai_activated: "👨‍⚕️ AI GUIDANCE ACTIVATED:",
    critical_error: "❌ CRITICAL ERROR: ",
    geo_denied: "❌ GEOLOCATION DENIED: RastaSaathi requires GPS to route to hospitals.",

    // Profile
    manage_grid: "Manage your identity and emergency response grid.",
    full_name: "Full Name",
    lang_priority: "Language Priority",
    emergency_contacts: "Emergency Contacts",
    recipients_sos: "Recipients of your automated SOS alerts.",
    add_new: "Add New",
    save_grid: "SAVE GRID CHANGES",
    no_contacts: "No emergency contacts detected.",
    add_one_contact: "Add at least one contact to enable WhatsApp SOS alerts.",

    // Auth
    login_title: "Welcome Back",
    login_sub: "Sign in to your RastaSaathi account",
    register_title: "Create Account",
    register_sub: "Join RastaSaathi today",
    email_label: "Email Address",
    password_label: "Password",
    signin_btn: "Sign In",
    register_btn: "Create Account",
    google_btn: "Sign in with Google",
    no_account: "Don't have an account?",
    have_account: "Already have an account?",

    // Footer
    footer_tagline: "Bridging the gap between accident and care.",
    hackathon_tag: "IIT MADRAS ROAD SAFETY HACKATHON 2026",
    contact_email: "rastasaathi@gmail.com",
    contact_phone: "+91 9441921812",
    made_with: "Made with",
    by_team: "by Team-RastaSaathi",
    official_protocol: "OFFICIAL EMERGENCY PROTOCOL",
    golden_minute_title: "The Golden Minute",
    golden_minute_sub: "In an emergency, every second counts. Follow these protocols while help is on the way. RastaSaathi is designed to occupy the 'Golden Hour' with absolute technical precision.",
    guide_usage_title: "Setup Demo Alerts (Crucial for Judges)",
    guide_use_step1_title: "1. Save Number",
    guide_use_step1_desc: "Save +1 415 523 8886 to your contacts as 'RastaSaathi Alerts'.",
    guide_use_step2_title: "2. Send Join Code",
    guide_use_step2_desc: "Send the WhatsApp message 'join' followed by the code below to that number.",
    guide_use_step3_title: "3. Direct WhatsApp Link",
    guide_use_step3_desc: "Use this button to quickly join our automated emergency alert grid.",
    guide_use_step4_title: "4. Add Your Phone",
    guide_use_step4_desc: "In the App, go to Profile and add your phone number with country code.",
    guide_use_step5_title: "5. Trigger SOS",
    guide_use_step5_desc: "Open RastaSaathi and tap the SOS button to alert emergency services and family.",
    guide_use_step6_title: "6. Use AI Medic",
    guide_use_step6_desc: "Keep the AI Medic chat open for specific first-aid instructions based on injuries.",
    human_impact: "The Human Impact",
    strategic_partnerships: "Strategic Partnerships",
    emergency_liaison: "Emergency Liaison",
    headquarters: "Headquarters",
    direct_support: "Direct Support",
    direct_support_sub: "If you are a medical professional or emergency responder looking to integrate with our grid, please reach out directly via email.",
    contact_us_now: "Contact Us Now",
    safety_first: "Safety First Protocol",
    safety_assist_text: "RastaSaathi is a tool to assist, not a substitute for professional medical help. Always ensure 108/112 has been notified.",
    do_not: "DO NOT",
    do: "DO",
    do_not_move: "Move victims of high-speed impacts unless there is immediate fire danger.",
    do_stay_line: "Stay on the line with our AI triage until the ambulance arrives.",
    connect_now: "Connect Now",
    zero_delay: "Zero Delay",
    zero_delay_desc: "Automated dispatch in <2 seconds.",
    scale: "Scale",
    scale_desc: "Deployable across any municipal grid.",
    excellence: "Excellence",
    excellence_desc: "Medical accuracy verified by experts.",

    // Mission
    mission_page_title: "Mission & Purpose",
    mission_page_sub: "Built for the IIT Madras Road Safety Hackathon 2026. Our mission is to eliminate the 'Golden Hour' delay in road accident response using Artificial Intelligence and automated dispatch systems.",
    mission_v_title: "Our Vision",
    mission_v_desc: "A future where road accident fatalities are eliminated through immediate, intelligent medical coordination.",
    mission_m_title: "Our Mission",
    mission_m_desc: "To leverage AI and geospatial data to provide instant triage and connect victims with the right care in the golden hour.",
    impact_sub: "Behind every line of code at RastaSaathi is a commitment to saving a life. We believe that in the age of AI, no person should die because an ambulance took too long or a hospital wasn't ready.",
    mission_manifesto: "THE RASTASAATHI MANIFESTO",

    // About
    origin_tech: "ORIGIN & TECHNOLOGY",
    about_vision_title: "The Architecture",
    about_vision_desc: "Revolutionizing road safety through AI-powered emergency response and real-time trauma care orchestration.",
    feature_ai_title: "AI Triage Engine",
    about_tech_desc: "Dual-model fallback architecture utilizing Anthropic Claude 3.5 Sonnet and Google Gemini 1.5 Flash to instantly predict injury severity and provide interactive first-aid guidance.",
    feature_route_title: "Geospatial Routing",
    feature_route_desc: "Powered by MongoDB $near queries and Google Maps API. We don't just find the closest hospital, we find the closest hospital equipped for your specific medical severity.",
    response_gap_title: "The Strategy",
    response_gap_p1: "By integrating AI directly into the dispatch workflow, we eliminate the 'human-in-the-loop' delay that often costs lives. Our strategy is focused on Zero-Latency response.",
    response_gap_p2: "We partner with local hospitals to create a real-time 'Medical Grid' where every second is accounted for and every resource is optimized.",
    verified_protocols: "Verified Protocols",
    verified_protocols_desc: "Emergency response mapped to national medical standards.",
    data_security: "Data Security",
    data_security_desc: "Encryption-first approach to victim telemetry.",
    citizen_first: "Citizen First",
    citizen_first_desc: "Designed to be accessible in high-stress situations.",
    latency: "Latency",
    stats_hospitals: "Integrated Hospitals",
    stats_responders: "Responders",
    project_stage: "Project Stage"
  },
  hi: {
    // Navigation
    home: "होम",
    about: "हमारे बारे में",
    guide: "मार्गदर्शिका",
    contact: "संपर्क",
    dashboard: "डैशबोर्ड",
    login: "लॉगिन",
    logout: "लॉगआउट",
    profile: "प्रोफ़ाइल",
    road_safety: "सुरक्षा दिशानिर्देश",
    vision_mission: "विज़न और मिशन",
    language_label: "भाषा",
    navigation: "नेविगेशन",

    // Home Page
    hero_title: "सेकंड जान बचाते हैं।",
    hero_sub: "रास्तासाथी दुर्घटना और जीवन रक्षक देखभाल के बीच की दूरी को पाटने के लिए एआई और रीयल-टाइम अलर्ट का उपयोग करता है।",
    view_guide: "आपातकालीन मार्गदर्शिका देखें",
    vision: "हमारा दृष्टिकोण",
    national_initiative: "राष्ट्रीय सड़क सुरक्षा पहल",
    precision_eng: "सटीक इंजीनियरिंग",
    impact_title: "हर नागरिक को सशक्त बनाना",
    results_title: "परिणामों के लिए इंजीनियर।",
    journey_title: "सुरक्षा के 3 कदम",
    journey_sub: "तकनीक और चिकित्सा विशेषज्ञता का एक सटीक समन्वय।",
    step1_title: "SOS ट्रिगर करें",
    step1_desc: "प्रोटोकॉल शुरू करने के लिए आपातकालीन बटन दबाएं। हम सटीक GPS डेटा कैप्चर करते हैं।",
    step2_title: "AI मूल्यांकन",
    step2_desc: "हमारा मेडिकल इंजन चोट की गंभीरता और अस्पताल की जरूरतों की पहचान करता है।",
    step3_title: "बचाव शुरू",
    step3_desc: "निकटतम अस्पताल को सतर्क किया जाता है और नेविगेशन तुरंत शुरू होता है।",
    join_national_mission: "राष्ट्रीय मिशन में शामिल हों",
    become_responder: "उत्तरदाता बनें",

    // Dashboard
    secure_terminal: "सुरक्षित आपातकालीन टर्मिनल",
    ready_dispatch: "प्रेषण के लिए तैयार।",
    trigger_sub: "तत्काल भू-स्थानिक जांच और आपातकालीन अलर्ट के लिए SOS ट्रिगर करें।",
    sos_active: "SOS सक्रिय",
    geospatial_grid: "भू-स्थानिक ग्रिड",
    system_status: "सिस्टम की स्थिति",
    sync_grid: "ग्रिड को सिंक्रोनाइज़ कर रहा है...",
    dispatched_alerts: "अलर्ट भेजे गए।",
    target_center: "लक्ष्य केंद्र",
    calculating: "गणना कर रहा है...",
    ai_medic: "AI मेडिक",
    emergency_guidance: "आपातकालीन मार्गदर्शन...",
    medic_welcome: "रास्तासाथी एआई मेडिक सक्रिय है। मैं आपके ग्रिड की निगरानी कर रहा हूँ।",
    initiating_protocol: "आपातकालीन प्रोटोकॉल शुरू: GPS डेटा प्राप्त कर रहा है...",
    gps_acquired: "📍 GPS निर्देशांक प्राप्त: ",
    sync_national: "राष्ट्रीय चिकित्सा ग्रिड के साथ सिंक्रोनाइज़ कर रहा है...",
    sos_success: "✅ SOS सफलतापूर्वक भेजा गया!",
    contacts_notified: "📲 आपातकालीन संपर्कों को व्हाट्सएप अलर्ट भेजे गए।",
    nearest_hospital: "🏥 निकटतम अस्पताल: ",
    eta: "⏳ आगमन का समय: ",
    no_hospitals: "⚠️ अलर्ट: SOS ट्रिगर हुआ, लेकिन आसपास कोई अस्पताल नहीं मिला।",
    ai_activated: "👨‍⚕️ AI मार्गदर्शन सक्रिय:",
    critical_error: "❌ गंभीर त्रुटि: ",
    geo_denied: "❌ स्थान अस्वीकृत: रास्तासाथी को अस्पतालों के लिए GPS की आवश्यकता है।",

    // Profile
    manage_grid: "अपनी पहचान और आपातकालीन प्रतिक्रिया ग्रिड प्रबंधित करें।",
    full_name: "पूरा नाम",
    lang_priority: "भाषा प्राथमिकता",
    emergency_contacts: "आपातकालीन संपर्क",
    recipients_sos: "आपके स्वचालित SOS अलर्ट प्राप्तकर्ता।",
    add_new: "नया जोड़ें",
    save_grid: "परिवर्तन सहेजें",
    no_contacts: "कोई आपातकालीन संपर्क नहीं मिला।",
    add_one_contact: "व्हाट्सएप अलर्ट सक्षम करने के लिए कम से कम एक संपर्क जोड़ें।",

    // Auth
    login_title: "स्वागत है",
    login_sub: "अपने रास्तासाथी खाते में साइन इन करें",
    register_title: "खाता बनाएं",
    register_sub: "आज ही रास्तासाथी से जुड़ें",
    email_label: "ईमेल पता",
    password_label: "पासवर्ड",
    signin_btn: "साइन इन करें",
    register_btn: "खाता बनाएं",
    google_btn: "गूगल के साथ साइन इन करें",
    no_account: "खाता नहीं है?",
    have_account: "पहले से ही एक खाता है?",

    // Footer
    footer_tagline: "दुर्घटना और देखभाल के बीच की दूरी को पाटना।",
    hackathon_tag: "IIT मद्रास रोड सेफ्टी हैकाथॉन 2026",
    contact_email: "rastasaathi@gmail.com",
    contact_phone: "+91 9441921812",
    made_with: "बनाया गया है",
    by_team: "रास्तासाथी टीम द्वारा",
    official_protocol: "आधिकारिक आपातकालीन प्रोटोकॉल",
    golden_minute_title: "स्वर्णिम मिनट",
    golden_minute_sub: "सड़क दुर्घटना के पहले 60 सेकंड जीवित रहने के परिणाम को निर्धारित करते हैं।",
    human_impact: "मानवीय प्रभाव",
    strategic_partnerships: "रणनीतिक साझेदारी",
    emergency_liaison: "आपातकालीन संपर्क",
    headquarters: "मुख्यालय",
    direct_support: "प्रत्यक्ष समर्थन",
    direct_support_sub: "यदि आप एक चिकित्सा पेशेवर या आपातकालीन उत्तरदाता हैं, तो कृपया ईमेल के माध्यम से संपर्क करें।",
    contact_us_now: "अभी हमसे संपर्क करें",
    safety_first: "सुरक्षा प्रथम प्रोटोकॉल",
    safety_assist_text: "रास्तासाथी एक सहायता उपकरण है, चिकित्सा सहायता का विकल्प नहीं।",
    do_not: "न करें",
    do: "करें",
    do_not_move: "पीड़ित को तब तक न हिलाएं जब तक आग का खतरा न हो।",
    do_stay_line: "एम्बुलेंस आने तक लाइन पर बने रहें।",
    connect_now: "अभी जुड़ें",
    zero_delay: "शून्य विलंब",
    zero_delay_desc: "शून्य विलंब प्रेषण <2s.",
    scale: "स्केल",
    scale_desc: "नगरपालिका ग्रिड में तैनात करने योग्य।",
    excellence: "उत्कृष्टता",
    excellence_desc: "चिकित्सा सटीकता।"
  },
  te: {
    home: "హోమ్",
    about: "మా గురించి",
    guide: "గైడ్",
    contact: "సంప్రదించండి",
    dashboard: "డాష్‌బోర్డ్",
    login: "లాగిన్",
    logout: "లాగౌట్",
    profile: "ప్రొఫైల్",
    road_safety: "భద్రతా మార్గదర్శకాలు",
    vision_mission: "దృష్టి & లక్ష్యం",
    language_label: "భాష",
    navigation: "నావిగేషన్",
    hero_title: "క్షణాలు ప్రాణాలను కాపాడతాయి.",
    hero_sub: "ప్రమాదానికి మరియు ప్రాణరక్షక సంరక్షణకు మధ్య ఉన్న అంతరాన్ని పూడ్చడానికి రాస్తాసాథీ ఏఐని ఉపయోగిస్తుంది.",
    view_guide: "ఎమర్జెన్సీ గైడ్ చూడండి",
    vision: "మా దృష్టి",
    register_btn: "ఖాతాను సృష్టించండి",
    full_name: "పూర్తి పేరు",
    save_grid: "మార్పులను సేవ్ చేయండి"
  },
  ta: {
    home: "முகப்பு",
    about: "எங்களைப் பற்றி",
    guide: "வழிகாட்டி",
    contact: "தொடர்பு",
    dashboard: "டாஷ்போர்டு",
    login: "உள்நுழைவு",
    logout: "வெளியேறுதல்",
    profile: "சுயவிவரம்",
    road_safety: "பாதுகாப்பு வழிகாட்டுதல்கள்",
    vision_mission: "பார்வையும் நோக்கமும்",
    language_label: "மொழி",
    navigation: "வழிசெலுத்தல்",
    hero_title: "நொடிகள் உயிர்களைக் காக்கின்றன.",
    hero_sub: "விபத்துக்கும் உயிர்காக்கும் சிகிச்சைக்கும் இடையிலான இடைவெளியைக் குறைக்க ராஸ்தாசாத்தி உதவுகிறது.",
    view_guide: "அவசர வழிகாட்டியைப் பார்க்கவும்",
    vision: "எங்கள் பார்வை",
    register_btn: "கணக்கை உருவாக்கு",
    full_name: "முழு பெயர்",
    save_grid: "மாற்றங்களைச் சேமிக்கவும்"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en');

  const t = (key) => {
    return TRANSLATIONS[lang]?.[key] || TRANSLATIONS['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
