import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const TRANSLATIONS = {
  en: {
    home: "Home",
    about: "About",
    guide: "Guide",
    contact: "Contact",
    dashboard: "Dashboard",
    login: "Login",
    logout: "Logout",
    hero_title: "Seconds Save Lives.",
    hero_sub: "RastaSaathi orchestrates AI, geospatial data, and real-time alerts to bridge the gap between accident and life-saving care.",
    view_guide: "View Emergency Guide",
    vision: "Our Vision",
    vision_mission: "Vision & Mission",
    medic_title: "MEDIC",
    mission_page_title: "The RastaSaathi Mission",
    mission_page_sub: "Establishing a national-scale medical grid where zero lives are lost to road accidents due to medical delay.",
    mission_v_title: "The National Vision",
    mission_v_desc: "To engineer a globally recognized, AI-powered emergency infrastructure that eliminates the 'Response Gap' across all Indian highways and urban centers.",
    mission_m_title: "The Strategic Mission",
    mission_m_desc: "To synchronize millisecond precision in geospatial hospital routing with AI-driven injury triage, ensuring every citizen receives care within the 'Golden Minute'.",
    medic_welcome: "RastaSaathi AI Medic activated. I am here to provide instant first-aid protocols. What is the emergency?",
    immediate_action: "Immediate Action",
    call_108: "CALL 108 NOW",
    first_aid_label: "FIRST AID",
    avoid_label: "AVOID",
    stats_responders: "Active Responders",
    stats_protocols: "Emergency Protocols",
    stats_hospitals: "Hospitals Mapped",
    feature_ai_title: "AI-Powered Triage",
    feature_ai_desc: "Real-time severity assessment using Google Gemini Vision.",
    feature_route_title: "Smart Hospital Routing",
    feature_route_desc: "Geospatial optimization to find the fastest medical care.",
    feature_alert_title: "Real-time SMS Alerts",
    feature_alert_desc: "Instant notification to family and nearest responders via Twilio.",
    select_emergency: "-- Select Emergency Type --",
    describe_situation: "Or describe situation...",
    severity_label: "SEVERITY",
    login_title: "Welcome Back",
    login_sub: "Sign in to your RastaSaathi account",
    register_title: "Create Account",
    register_sub: "Join RastaSaathi today",
    email_label: "Email Address",
    password_label: "Password",
    signin_btn: "Sign In",
    register_btn: "Create Account",
    google_btn: "Sign in with Google",
    no_account: "Don't have an account?",
    have_account: "Already have an account?",
    journey_title: "3 Steps to Safety",
    journey_sub: "A precision-engineered orchestration of technology and medical expertise.",
    step1_title: "Trigger SOS",
    step1_desc: "Tap the emergency button to start the protocol. We capture precise GPS coordinates and network triage data.",
    step2_title: "AI Assessment",
    step2_desc: "Our medical engine identifies injury severity and hospital needs using real-time inputs.",
    step3_title: "Rescue Commences",
    step3_desc: "The nearest hospital is alerted, emergency contacts are notified, and navigation starts instantly.",
    golden_minute_title: "The Golden Minute",
    golden_minute_sub: "Statistics show that the actions taken within the first 60 seconds of a road incident determine the survival outcome. RastaSaathi is designed to occupy this minute with absolute technical precision.",
    verified_protocols_title: "Verified Protocols",
    verified_protocols_sub: "Every instruction provided by RastaSaathi is cross-referenced with international emergency medicine standards, ensuring that first responders act with the authority of a surgeon.",
    mission_title: "Built by Visionaries",
    mission_sub: "RastaSaathi was born out of the IIT Madras Road Safety Hackathon with a single objective: to eliminate the 'Response Gap' in Indian road emergencies.",
    global_title: "Supporting the Global Community",
    global_sub: "RastaSaathi is more than a regional tool; it is a blueprint for scalable municipal emergency response. We are partnering with cities to integrate AI directly into the local medical grid.",
    tech_sub: "Our system runs on a high-availability infrastructure designed for <2s latency in mission-critical environments.",
    immediate_action_desc: "Upon triggering the SOS, follow the visualized medical prompts on your dashboard immediately while help is in transit.",
    contact_email: "rastasaathi@gmail.com",
    contact_phone: "+91 9441921812",
    contact_address: "IIT Madras Research Park, Chennai, India",
    impact_title: "Empowering Every Citizen",
    impact_sub: "RastaSaathi turns every smartphone into a life-saving terminal. By democratizing emergency response, we ensure that no accident victim is ever left alone during the Golden Minute.",
    eco_title: "The Medical Ecosystem",
    eco_sub: "We bridge the gap between GPS data, AI severity assessment, and hospital resource management to create a seamless rescue loop.",
    about_tech_title: "The Core Technology",
    about_tech_desc: "Utilizing Google Gemini Vision for real-time injury assessment and advanced geospatial algorithms for millisecond-precision hospital routing.",
    about_vision_title: "Our Journey",
    about_vision_desc: "Born in the IIT Madras Road Safety Hackathon 2026, RastaSaathi was designed to solve the critical delay in Indian emergency response systems.",
    guide_triage_title: "Advanced Triage Protocol",
    guide_triage_desc: "Our AI categorizes incidents into Red (Critical), Yellow (Serious), and Green (Stable) to prioritize hospital resources effectively.",
    guide_evac_title: "Safe Evacuation",
    guide_evac_desc: "Never move a victim with potential spinal injuries. Wait for professional paramedics unless the environment is life-threatening (e.g., fire).",
    guide_usage_title: "Step-by-Step User Journey",
    guide_use_step1_title: "1. Secure Registration",
    guide_use_step1_desc: "Start by creating your secure RastaSaathi account. This ensures your medical profile and identity are authenticated for emergency services.",
    guide_use_step2_title: "2. Profile & Contacts",
    guide_use_step2_desc: "Enter your blood group, allergies, and emergency contact numbers. These details are instantly shared with hospitals when you trigger an SOS.",
    guide_use_step3_title: "3. WhatsApp Demo Sync",
    guide_use_step3_desc: "Send 'Join do-hit' to our sandbox number. This is critical for the demo to receive real-time notifications on your phone.",
    guide_use_step4_title: "4. Triggering the SOS",
    guide_use_step4_desc: "In an emergency, open your Dashboard and tap the 'Trigger SOS' button. The AI immediately captures your precise GPS coordinates.",
    guide_use_step5_title: "5. AI Triage Assessment",
    guide_use_step5_desc: "Our AI engine analyzes the incident severity and notifies the nearest available hospital with your medical profile in milliseconds.",
    guide_use_step6_title: "6. Real-time Navigation",
    guide_use_step6_desc: "Once a hospital is assigned, you receive a dynamic navigation HUD to the ER, while responders receive your live telemetry.",
    impact_feature1: "Network Triage",
    impact_feature2: "Real-time Telemetry",
    impact_feature3: "Predictive Triage",
    whatsapp_title: "WhatsApp Integration",
    whatsapp_desc: "To receive real-time demo alerts on WhatsApp, send 'Join do-hit' to our sandbox number:",
    whatsapp_number: "+1 (415) 523-8886",
    footer_tagline: "Bridging the gap between accident and care.",
    orch_title: "Precision Medical Orchestration",
    orch_feature1_title: "Geospatial Triage",
    orch_feature1_desc: "AI-driven hospital selection based on real-time traffic, proximity, and ER capacity.",
    orch_feature2_title: "Zero-Latency Dispatch",
    orch_feature2_desc: "Simultaneous alerting of hospitals, responders, and family in under 2 seconds.",
    orch_feature3_title: "Secure Medical Grid",
    orch_feature3_desc: "Encrypted delivery of your medical history to trauma surgeons before you arrive.",
    hackathon_tag: "IIT MADRAS ROAD SAFETY HACKATHON 2026",
    trust_support: "SUPPORTING NATIONAL SAFETY INITIATIVES",
    tech_superiority: "TECHNICAL SUPERIORITY",
    faster_response: "FASTER RESPONSE",
    hospitals_grid: "HOSPITALS IN GRID",
    latency: "LATENCY",
    engineered_capabilities: "Engineered Capabilities",
    dynamic_routing: "Dynamic Geospatial Routing",
    ai_severity: "AI Severity Scoring",
    join_national_mission: "Join the National Mission",
    become_responder: "Become a Responder",
    email_support: "EMAIL SUPPORT",
    emergency_hotline: "EMERGENCY HOTLINE",
    hackathon_id: "HACKATHON ID",
    official_protocol: "OFFICIAL EMERGENCY PROTOCOL",
    safety_first: "Safety First Protocol",
    safety_assist_text: "RastaSaathi is a tool to assist, not a substitute for professional medical help. Always ensure 108/112 has been notified.",
    do_not: "DO NOT",
    do: "DO",
    do_not_move: "Move victims of high-speed impacts unless there is immediate fire danger.",
    do_stay_line: "Stay on the line with our AI triage until the ambulance arrives.",
    origin_tech: "OUR ORIGIN & TECHNOLOGY",
    response_gap_title: "The 'Response Gap' Problem",
    response_gap_p1: "In India, thousands of lives are lost every year because medical help arrives just minutes too late.",
    response_gap_p2: "RastaSaathi automates this entire loop, synchronizing responders and hospitals in under 2 seconds.",
    verified_protocols: "Verified Protocols",
    verified_protocols_desc: "International standards cross-referenced.",
    data_security: "Data Security",
    data_security_desc: "HIPAA-compliant medical data handling.",
    citizen_first: "Citizen First",
    citizen_first_desc: "Designed for the stressed first responder.",
    project_stage: "Project Stage",
    mvp_plus: "MVP++",
    mission_manifesto: "THE RASTASAATHI MANIFESTO",
    zero_delay: "Zero Delay",
    zero_delay_desc: "Automated dispatch in <2 seconds.",
    scale: "Scale",
    scale_desc: "Deployable across any municipal grid.",
    excellence: "Excellence",
    excellence_desc: "Medical accuracy verified by experts.",
    connect_now: "Connect Now",
    navigation: "NAVIGATION",
    language_label: "LANGUAGE"
  },
  hi: {
    home: "होम",
    about: "हमारे बारे में",
    guide: "मार्गदर्शिका",
    contact: "संपर्क",
    dashboard: "डैशबोर्ड",
    login: "लॉगिन",
    logout: "लॉगआउट",
    hero_title: "सेकंड जान बचाते हैं।",
    hero_sub: "रास्तासाथी दुर्घटना और जीवन रक्षक देखभाल के बीच की दूरी को पाटने के लिए एआई और रीयल-टाइम अलर्ट का उपयोग करता है।",
    view_guide: "आपातकालीन मार्गदर्शिका देखें",
    vision: "हमारा दृष्टिकोण",
    vision_mission: "विज़न और मिशन",
    medic_title: "मेडिक",
    mission_page_title: "रास्तासाथी मिशन",
    mission_page_sub: "एक राष्ट्रीय स्तर का मेडिकल ग्रिड जहां चिकित्सा विलंब के कारण सड़क दुर्घटनाओं में शून्य जान चली जाए।",
    mission_v_title: "राष्ट्रीय विजन",
    mission_v_desc: "एक वैश्विक स्तर पर मान्यता प्राप्त, एआई-संचालित आपातकालीन बुनियादी ढांचा तैयार करना।",
    mission_m_title: "रणनीतिक मिशन",
    mission_m_desc: "एआई-संचालित चोट जांच के साथ भू-स्थानिक अस्पताल रूटिंग में मिलीसेकंड सटीकता को सिंक्रनाइज़ करना।",
    medic_welcome: "रास्तासाथी एआई मेडिक सक्रिय है। मैं प्राथमिक चिकित्सा प्रोटोकॉल प्रदान करने के लिए यहां हूं।",
    immediate_action: "तत्काल कार्रवाई",
    call_108: "अभी 108 पर कॉल करें",
    first_aid_label: "प्राथमिक चिकित्सा",
    avoid_label: "बचें",
    stats_responders: "सक्रिय उत्तरदाता",
    stats_protocols: "आपातकालीन प्रोटोकॉल",
    stats_hospitals: "अस्पताल मैप किए गए",
    feature_ai_title: "एआई-संचालित जांच",
    feature_ai_desc: "रीयल-टाइम गंभीरता मूल्यांकन।",
    feature_route_title: "स्मार्ट अस्पताल रूटिंग",
    feature_route_desc: "सबसे तेज़ चिकित्सा देखभाल खोजने के लिए भू-स्थानिक अनुकूलन।",
    feature_alert_title: "रीयल-टाइम एसएमएस अलर्ट",
    feature_alert_desc: "ट्विलियो के माध्यम से परिवार और उत्तरदाताओं को सूचना।",
    select_emergency: "-- आपातकालीन प्रकार चुनें --",
    describe_situation: "या स्थिति का वर्णन करें...",
    severity_label: "गंभीरता",
    login_title: "स्वागत है",
    login_sub: "अपने रास्तासाथी खाते में साइन इन करें",
    register_title: "खाता बनाएं",
    register_sub: "आज ही रास्तासाथी से जुड़ें",
    email_label: "ईमेल पता",
    password_label: "पासवर्ड",
    signin_btn: "साइन इन करें",
    register_btn: "खाता बनाएं",
    google_btn: "गूगल के साथ साइन इन करें",
    no_account: "खाता नहीं है?",
    have_account: "पहले से ही एक खाता है?",
    journey_title: "सुरक्षा के 3 कदम",
    journey_sub: "तकनीक और चिकित्सा विशेषज्ञता का एक सटीक समन्वय।",
    step1_title: "SOS ट्रिगर करें",
    step1_desc: "प्रोटोकॉल शुरू करने के लिए आपातकालीन बटन दबाएं।",
    step2_title: "AI मूल्यांकन",
    step2_desc: "हमारा मेडिकल इंजन चोट की गंभीरता की पहचान करता है।",
    step3_title: "बचाव शुरू",
    step3_desc: "निकटतम अस्पताल को सतर्क किया जाता है।",
    golden_minute_title: "स्वर्णिम मिनट",
    golden_minute_sub: "सड़क दुर्घटना के पहले 60 सेकंड जीवित रहने के परिणाम को निर्धारित करते हैं।",
    verified_protocols_title: "सत्यापित प्रोटोकॉल",
    verified_protocols_sub: "अंतर्राष्ट्रीय आपातकालीन चिकित्सा मानकों के साथ क्रॉस-रेफरेंस।",
    mission_title: "दूरदर्शी लोगों द्वारा निर्मित",
    mission_sub: "रास्तासाथी का जन्म भारतीय सड़क आपात स्थितियों में प्रतिक्रिया अंतर को समाप्त करने के लिए हुआ था।",
    global_title: "वैश्विक समुदाय का समर्थन",
    global_sub: "रास्तासाथी एक स्केलेबल नगरपालिका आपातकालीन प्रतिक्रिया के लिए एक खाका है।",
    tech_sub: "मिशन-महत्वपूर्ण वातावरण में <2s विलंबता।",
    immediate_action_desc: "SOS शुरू करने पर, डैशबोर्ड पर मेडिकल प्रॉम्प्ट्स का तुरंत पालन करें।",
    contact_email: "rastasaathi@gmail.com",
    contact_phone: "+91 9441921812",
    contact_address: "IIT मद्रास रिसर्च पार्क, चेन्नई, भारत",
    impact_title: "हर नागरिक को सशक्त बनाना",
    impact_sub: "रास्तासाथी हर स्मार्टफोन को जीवन रक्षक टर्मिनल में बदल देता है।",
    eco_title: "चिकित्सा पारिस्थितिकी तंत्र",
    eco_sub: "हम GPS डेटा और अस्पताल संसाधन प्रबंधन के बीच की दूरी को पाटते हैं।",
    about_tech_title: "मुख्य तकनीक",
    about_tech_desc: "रीयल-टाइम चोट मूल्यांकन के लिए गूगल जेमिनी विजन।",
    about_vision_title: "हमारी यात्रा",
    about_vision_desc: "IIT मद्रास रोड सेफ्टी हैकाथॉन 2026 में जन्मा।",
    guide_triage_title: "उन्नत जांच प्रोटोकॉल",
    guide_triage_desc: "AI अस्पताल के संसाधनों को प्राथमिकता देने के लिए घटनाओं को वर्गीकृत करता है।",
    guide_evac_title: "सुरक्षित निकासी",
    guide_evac_desc: "रीढ़ की हड्डी की चोट वाले पीड़ित को कभी न हिलाएं।",
    guide_usage_title: "चरण-दर-चरण उपयोगकर्ता यात्रा",
    guide_use_step1_title: "1. सुरक्षित पंजीकरण",
    guide_use_step1_desc: "अपना सुरक्षित रास्तासाथी खाता बनाकर शुरुआत करें।",
    guide_use_step2_title: "2. प्रोफ़ाइल और संपर्क",
    guide_use_step2_desc: "अपना रक्त समूह और आपातकालीन संपर्क दर्ज करें।",
    guide_use_step3_title: "3. व्हाट्सएप डेमो सिंक",
    guide_use_step3_desc: "हमारे सैंडबॉक्स नंबर पर 'Join do-hit' भेजें।",
    guide_use_step4_title: "4. SOS ट्रिगर करना",
    guide_use_step4_desc: "अपना डैशबोर्ड खोलें और बटन दबाएं।",
    guide_use_step5_title: "5. एआई जांच मूल्यांकन",
    guide_use_step5_desc: "एआई इंजन गंभीरता का विश्लेषण करता है।",
    guide_use_step6_title: "6. रीयल-टाइम नेविगेशन",
    guide_use_step6_desc: "आपको ER के लिए नेविगेशन प्राप्त होता है।",
    impact_feature1: "नेटवर्क जांच",
    impact_feature2: "रीयल-टाइम टेलीमेट्री",
    impact_feature3: "भविष्य कहनेवाला जांच",
    whatsapp_title: "व्हाट्सएप एकीकरण",
    whatsapp_desc: "व्हाट्सएप पर अलर्ट प्राप्त करने के लिए 'Join do-hit' भेजें:",
    whatsapp_number: "+1 (415) 523-8886",
    footer_tagline: "दुर्घटना और देखभाल के बीच की दूरी को पाटना।",
    orch_title: "सटीक चिकित्सा ऑर्केस्ट्रेशन",
    orch_feature1_title: "भू-स्थानिक जांच",
    orch_feature1_desc: "रीयल-टाइम ट्रैफ़िक के आधार पर एआई चयन।",
    orch_feature2_title: "शून्य-विलंबता प्रेषण",
    orch_feature2_desc: "2 सेकंड से कम समय में अलर्ट।",
    orch_feature3_title: "सुरक्षित चिकित्सा ग्रिड",
    orch_feature3_desc: "एन्क्रिप्टेड मेडिकल इतिहास वितरण।",
    hackathon_tag: "IIT मद्रास रोड सेफ्टी हैकाथॉन 2026",
    trust_support: "राष्ट्रीय सुरक्षा पहल का समर्थन",
    tech_superiority: "तकनीकी श्रेष्ठता",
    faster_response: "तेज़ प्रतिक्रिया",
    hospitals_grid: "ग्रिड में अस्पताल",
    latency: "विलंबता",
    engineered_capabilities: "इंजीनियर्ड क्षमताएं",
    dynamic_routing: "गतिशील भू-स्थानिक रूटिंग",
    ai_severity: "एआई गंभीरता स्कोरिंग",
    join_national_mission: "राष्ट्रीय मिशन में शामिल हों",
    become_responder: "उत्तरदाता बनें",
    email_support: "ईमेल समर्थन",
    emergency_hotline: "आपातकालीन हॉटलाइन",
    hackathon_id: "हैकाथॉन आईडी",
    official_protocol: "आधिकारिक आपातकालीन प्रोटोकॉल",
    safety_first: "सुरक्षा प्रथम प्रोटोकॉल",
    safety_assist_text: "रास्तासाथी एक सहायता उपकरण है, चिकित्सा सहायता का विकल्प नहीं।",
    do_not: "न करें",
    do: "करें",
    do_not_move: "पीड़ित को तब तक न हिलाएं जब तक आग का खतरा न हो।",
    do_stay_line: "एम्बुलेंस आने तक लाइन पर बने रहें।",
    origin_tech: "हमारा मूल और तकनीक",
    response_gap_title: "प्रतिक्रिया अंतर की समस्या",
    response_gap_p1: "भारत में हर साल हजारों जानें चिकित्सा सहायता में देरी के कारण जाती हैं।",
    response_gap_p2: "रास्तासाथी 2 सेकंड से कम समय में पूरी प्रक्रिया को स्वचालित करता है।",
    verified_protocols: "सत्यापित प्रोटोकॉल",
    verified_protocols_desc: "अंतर्राष्ट्रीय मानक।",
    data_security: "डेटा सुरक्षा",
    data_security_desc: "चिकित्सा डेटा हैंडलिंग।",
    citizen_first: "नागरिक प्रथम",
    citizen_first_desc: "तनावग्रस्त उत्तरदाताओं के लिए डिज़ाइन किया गया।",
    project_stage: "परियोजना चरण",
    mvp_plus: "एमवीपी++",
    mission_manifesto: "रास्तासाथी घोषणापत्र",
    zero_delay: "शून्य विलंब",
    zero_delay_desc: "स्वचालित प्रेषण <2s.",
    scale: "स्केल",
    scale_desc: "नगरपालिका ग्रिड में तैनात करने योग्य।",
    excellence: "उत्कृष्टता",
    excellence_desc: "चिकित्सा सटीकता।",
    connect_now: "अभी जुड़ें",
    navigation: "नेविगेशन",
    language_label: "भाषा"
  },
  te: {
    home: "హోమ్",
    about: "మా గురించి",
    guide: "గైడ్",
    contact: "సంప్రదించండి",
    dashboard: "డాష్‌బోర్డ్",
    login: "లాగిన్",
    logout: "లాగౌట్",
    hero_title: "క్షణాలు ప్రాణాలను కాపాడతాయి.",
    hero_sub: "ప్రమాదానికి మరియు ప్రాణరక్షక సంరక్షణకు మధ్య ఉన్న అంతరాన్ని పూడ్చడానికి రాస్తాసాథీ ఏఐ, జియోస్పేషియల్ డేటా మరియు రియల్-టైమ్ హెచ్చరికలను సమన్వయం చేస్తుంది.",
    vision: "దృష్టి",
    vision_mission: "దృష్టి & లక్ష్యం",
    register_btn: "ఖాతాను సృష్టించండి"
  },
  ta: {
    home: "முகப்பு",
    about: "எங்களைப் பற்றி",
    guide: "வழிகாட்டி",
    contact: "தொடர்பு",
    dashboard: "டாஷ்போர்டு",
    login: "உள்நுழைவு",
    logout: "வெளியேறுதல்",
    hero_title: "நொடிகள் உயிர்களைக் காக்கின்றன.",
    hero_sub: "விபத்துக்கும் உயிர்காக்கும் சிகிச்சைக்கும் இடையிலான இடைவெளியைக் குறைப்பதற்காக, ராஸ்தாசாத்தி செயற்கை நுண்ணறிவு, புவிசார் தரவு மற்றும் நிகழ்நேர எச்சரிக்கைகளை ஒருங்கிணைக்கிறது.",
    vision: "பார்வை",
    vision_mission: "பார்வையும் நோக்கமும்",
    register_btn: "கணக்கை உருவாக்கு"
  },
  ur: {
    home: "گھر",
    about: "کے بارے में",
    guide: "گائیڈ",
    contact: "رابطہ کریں۔",
    dashboard: "ڈیش بورڈ",
    login: "لاگ ان",
    logout: "لاگ آؤٹ",
    hero_title: "سیکنڈز سیو لیز۔",
    hero_sub: "RastaSaathi حادثے اور جان بچانے والی دیکھ بھال کے درمیان فرق کو ختم کرنے کے لیے AI، جغرافیائی اعداد و شمار، اور حقیقی وقت کے انتباہات کو ترتیب دیتا ہے۔",
    vision: "وژن",
    vision_mission: "وژن اور مشن",
    register_btn: "اکاؤنٹ بنائیں"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en');

  const t = (key) => {
    return TRANSLATIONS[lang]?.[key] || TRANSLATIONS['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
