import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

const TRANSLATIONS = {
  en: {
    // Navigation
    home: "Home",
    about: "About",
    guide: "Guide",
    contact: "Contact",
    dashboard: "Dashboard",
    login: "Login",
    logout: "Logout",
    profile: "Profile",
    road_safety: "Safety Guidelines",
    vision_mission: "Vision & Mission",
    language_label: "Language",
    navigation: "Navigation",

    // Home Page
    hero_title: "When Every Second Counts, RastaSaathi Responds.",
    hero_sub: "RastaSaathi uses AI and real-time alerts to bridge the gap between accident and life-saving care.",
    view_guide: "View Guide",
    vision: "Our Vision",
    national_initiative: "National Road Safety Initiative",
    precision_eng: "Precision Engineering",
    impact_title: "Empowering Every Citizen",
    impact_sub: "Our technology combines high-frequency geospatial indexing with AI triage to ensure zero-latency emergency response.",
    results_title: "Engineered for Results.",
    journey_title: "The Safety Journey",
    journey_sub: "A precise coordination of technology and medical expertise.",
    step1_title: "Trigger SOS",
    step1_desc: "Press the emergency button to initiate protocols. We capture precision GPS data.",
    step2_title: "AI Assessment",
    step2_desc: "Our medical engine identifies injury severity and hospital requirements.",
    step3_title: "Rescue Initiated",
    step3_desc: "Nearest hospital is alerted and navigation starts immediately.",
    join_national_mission: "Join the National Mission",
    become_responder: "Become a Responder",

    // Dashboard
    secure_terminal: "Secure Emergency Terminal",
    ready_dispatch: "Ready for Dispatch.",
    trigger_sub: "Trigger SOS for immediate geospatial probe and emergency alerts.",
    sos_active: "SOS ACTIVE",
    geospatial_grid: "Geospatial Grid",
    system_status: "System Status",
    sync_grid: "Synchronizing Grid...",
    dispatched_alerts: "Alerts Dispatched.",
    target_center: "Target Center",
    calculating: "Calculating...",
    ai_medic: "AI Medic",
    emergency_guidance: "Emergency Guidance...",
    medic_welcome: "RastaSaathi AI Medic is active. I am monitoring your grid.",
    initiating_protocol: "Initiating Emergency Protocol: Acquiring GPS Data...",
    gps_acquired: "📍 GPS Coordinates Acquired: ",
    sync_national: "Synchronizing with National Medical Grid...",
    sos_success: "✅ SOS Dispatched Successfully!",
    contacts_notified: "📲 WhatsApp alerts sent to emergency contacts.",
    nearest_hospital: "🏥 Nearest Hospital: ",
    nearest_police: "🚓 Nearest Police: ",
    eta: "⏳ Estimated Arrival: ",
    no_hospitals: "⚠️ ALERT: SOS Triggered, but no hospitals found nearby.",
    ai_activated: "👨‍⚕️ AI Guidance Activated:",
    critical_error: "❌ Critical Error: ",
    geo_denied: "❌ Location Denied: RastaSaathi requires GPS for hospitals.",

    // Profile
    manage_grid: "Manage your identity and emergency response grid.",
    full_name: "Full Name",
    lang_priority: "Preferred Language",
    emergency_contacts: "Emergency Contacts",
    recipients_sos: "Your emergency contacts who will receive automated WhatsApp alerts.",
    add_new: "Add New",
    save_grid: "SAVE GRID CHANGES",
    no_contacts: "No contacts in your network yet.",
    add_one_contact: "Add at least one contact to enable WhatsApp SOS alerts.",

    // Auth
    login_title: "Secure Login",
    login_sub: "Access your RastaSaathi safety dashboard",
    register_title: "Join the Network",
    register_sub: "Create your profile to enable emergency services",
    email_label: "Email Address",
    password_label: "Security Password",
    signin_btn: "Login to Dashboard",
    register_btn: "Register",
    google_btn: "Continue with Google",
    no_account: "New to RastaSaathi?",
    have_account: "Already have an account?",

    // Footer
    footer_tagline: "Bridging the gap between accidents and life-saving care.",
    hackathon_tag: "IIT MADRAS ROAD SAFETY HACKATHON 2026",
    contact_email: "rastasaathi@gmail.com",
    contact_phone: "+91 944 192 1812",
    made_with: "Made with",
    by_team: "by Team-RastaSaathi",
    official_protocol: "OFFICIAL EMERGENCY PROTOCOL",
    golden_minute_title: "The Golden Minute",
    golden_minute_sub: "In an emergency, every second counts. RastaSaathi is designed to occupy the 'Golden Hour' with absolute technical precision.",
    human_impact: "Saving Lives Every Second.",
    impact_sub: "RastaSaathi orchestrates AI and geospatial data to reclaim the 'Golden Hour.' We eliminate bureaucracy so medical care arrives when it matters most.",
    strategic_partnerships: "Our Ecosystem",
    emergency_liaison: "Verified Trauma Grid",
    headquarters: "Command & Control Hub",
    direct_support: "Partner with Us",
    direct_support_sub: "Integrate with our grid to redefine emergency response.",
    contact_us_now: "Join the Mission",
    contact_sub: "Get in touch with our team for collaboration or support.",
    email_us: "Official Email",
    call_us: "Emergency Line",
    location: "Base Operations",
    send_message: "Submit Request",
    global_community_title: "A Global Safety Blueprint",
    global_community_sub: "RastaSaathi is designed to be a scalable, global solution for road safety.",
    stat_partnerships: "Hospitals Linked",
    stat_response: "Avg Response",
    stat_accuracy: "AI Precision",
    stat_active: "Active",
    stat_minimal: "Sub-Second",
    stat_99: "99.9%",
    safety_first: "Safety Protocol First",
    safety_assist_text: "RastaSaathi is a decision-support tool. In case of emergency, always call local emergency services (108/112) immediately.",
    do_not: "CRITICAL DON'TS",
    do: "CRITICAL DOS",
    do_not_move: "Do not move an injured person unless there is an immediate threat of fire or explosion.",
    do_stay_line: "Stay calm and follow the AI Medic's triage instructions until professionals arrive.",
    connect_now: "Join the Mission",
    zero_delay: "Zero Delay",
    zero_delay_desc: "Instant automated dispatch protocols.",
    scale: "Hyper-Scalable",
    scale_desc: "Cloud-native infrastructure for city-wide scale.",
    excellence: "Medical Accuracy",
    excellence_desc: "AI models trained on clinical emergency data.",

    // Core Tech
    orch_feature1_title: "Geospatial Intelligence",
    orch_feature1_desc: "Real-time matching of victims with verified trauma centers.",
    orch_feature2_title: "AI-Driven Triage",
    orch_feature2_desc: "Bypassing human dispatch delays with instant, high-precision injury assessment.",
    orch_feature3_title: "Trusted Safety Grid",
    orch_feature3_desc: "A verified network of responders, hospitals, and emergency services working in perfect sync.",

    // Mission
    mission_page_title: "Our Mission & Vision",
    mission_page_sub: "Developed for the IIT Madras Road Safety Hackathon 2026. We are redefining the future of emergency response through AI-driven orchestration.",
    mission_v_title: "The Vision",
    mission_v_desc: "A world where zero lives are lost to road accidents because technology ensures help arrives exactly when and where it's needed.",
    mission_m_title: "The Mission",
    mission_m_desc: "To empower citizens and emergency services with real-time AI triage and automated geospatial coordination.",
    impact_sub: "At RastaSaathi, we believe every life is precious. Our technology is built to fight for every second, ensuring that the 'Golden Hour' is never lost to bureaucracy or delay.",
    mission_manifesto: "THE SAFETY MANIFESTO",

    // About
    origin_tech: "OUR TECHNOLOGY STACK",
    about_vision_title: "The Infrastructure",
    about_vision_desc: "A high-performance ecosystem of AI models, geospatial databases, and real-time communication protocols.",
    feature_ai_title: "Intelligent Triage Core",
    about_tech_desc: "Our dual-model architecture leverages the power of Gemini and Claude to provide redundant, high-precision medical assessments in real-time.",
    feature_route_title: "Precision Routing",
    feature_route_desc: "Utilizing advanced geospatial indexing to match victims with specialized trauma centers based on live availability and equipment.",
    response_gap_title: "Closing the Response Gap",
    response_gap_p1: "Traditional emergency response relies on human dispatchers, which introduces latency. RastaSaathi automates this process, saving minutes that save lives.",
    verified_protocols: "Clinical Standards",
    verified_protocols_desc: "All AI protocols are aligned with international emergency standards.",
    data_security: "Enterprise Security",
    data_security_desc: "Victim data is protected with end-to-end encryption and strict privacy controls.",
    citizen_first: "User-Centric Design",
    citizen_first_desc: "An intuitive interface designed to work under extreme stress and low bandwidth.",
    latency: "Response Time",
    stats_hospitals: "Medical Centers",
    stats_responders: "Active Responders",
    project_stage: "Development Phase",

    // Guide Usage
    guide_usage_title: "How to Use RastaSaathi",
    guide_use_step1_title: "Create Safety Profile",
    guide_use_step1_desc: "Register and complete your medical profile. This ensures rescuers have critical health data during emergencies.",
    guide_use_step2_title: "Build Safety Network",
    guide_use_step2_desc: "Add your emergency contacts. They will receive automated WhatsApp alerts with your live location if you trigger an SOS.",
    guide_use_step3_title: "Activate WhatsApp Alerts",
    guide_use_step3_desc: "Join our automated alert grid. Send 'join soft-peace' to our Twilio number to enable real-time messaging.",
    guide_use_step4_title: "Trigger SOS Protocol",
    guide_use_step4_desc: "In an emergency, hit the SOS button. Our geospatial engine immediately matches you with the best available trauma center.",
    guide_use_step5_title: "Consult AI Medic",
    guide_use_step5_desc: "Use our dual-model AI triage to get instant first-aid guidance. Stabilize the victim while help is on the way.",
    guide_use_step6_title: "Follow Rescue Map",
    guide_use_step6_desc: "Track the dispatch in real-time. Follow the optimized routes to the nearest verified medical facility.",
    twilio_command: "Join soft-peace",
    severity_label: "Severity",
    first_aid_label: "First Aid Instructions",
    avoid_label: "What to Avoid",
    call_108: "Call 108 Emergency",
    select_emergency: "Select Emergency Type",
    describe_situation: "Describe the situation...",
    critical_severity: "Critical",
    high_severity: "High",
    medium_severity: "Medium",
    low_severity: "Low",
    protocol_for: "Protocol for",
    medic_fallback_msg: "I understand this is an emergency. Please pick from the list or type keywords like 'Bleeding' or 'Burn'. Always call 108 immediately.",
    
    // Road Safety Categories
    general_tips: "General Tips",
    pedestrian_safety: "For Pedestrians",
    driver_safety: "For Motor Vehicle Drivers",
    child_safety: "For Children",
    parent_safety: "For Parents"
  },
  hi: {
    // Navigation
    home: "होम",
    about: "हमारे बारे में",
    guide: "मार्गदर्शिका",
    contact: "संपर्क",
    dashboard: "डैशबोर्ड",
    login: "लॉगिन",
    logout: "लॉगआउट",
    profile: "प्रोफ़ाइल",
    road_safety: "सुरक्षा दिशानिर्देश",
    vision_mission: "विज़न और मिशन",
    language_label: "भाषा",
    navigation: "नेविगेशन",

    // Home Page
    hero_title: "जब हर सेकंड मायने रखता है, RastaSaathi प्रतिक्रिया देता है।",
    hero_sub: "रास्तासाथी दुर्घटना और जीवन रक्षक देखभाल के बीच की दूरी को पाटने के लिए एआई और रीयल-टाइम अलर्ट का उपयोग करता है।",
    view_guide: "मार्गदर्शिका देखें",
    vision: "दृष्टिकोण",
    national_initiative: "राष्ट्रीय सड़क सुरक्षा पहल",
    precision_eng: "सटीक इंजीनियरिंग",
    impact_title: "हर नागरिक को सशक्त बनाना",
    impact_sub: "हमारा तकनीक शून्य-विलंब आपातकालीन प्रतिक्रिया सुनिश्चित करने के लिए उच्च-आवृत्ति भू-स्थानिक अनुक्रमण के साथ एआई ट्राइएज को जोड़ती है।",
    results_title: "परिणामों के लिए इंजीनियर।",
    journey_title: "सुरक्षा का सफर",
    journey_sub: "तकनीक और चिकित्सा विशेषज्ञता का एक सटीक समन्वय।",
    step1_title: "SOS ट्रिगर करें",
    step1_desc: "प्रोटोकॉल शुरू करने के लिए आपातकालीन बटन दबाएं। हम सटीक GPS डेटा कैप्चर करते हैं।",
    step2_title: "AI मूल्यांकन",
    step2_desc: "हमारा मेडिकल इंजन चोट की गंभीरता और अस्पताल की जरूरतों की पहचान करता है।",
    step3_title: "बचाव शुरू",
    step3_desc: "निकटतम अस्पताल को सतर्क किया जाता है और नेविगेशन तुरंत शुरू होता है।",
    join_national_mission: "राष्ट्रीय मिशन में शामिल हों",
    become_responder: "उत्तरदाता बनें",

    // Dashboard
    secure_terminal: "सुरक्षित आपातकालीन टर्मिनल",
    ready_dispatch: "प्रेषण के लिए तैयार।",
    trigger_sub: "तत्काल भू-स्थानिक जांच और आपातकालीन अलर्ट के लिए SOS ट्रिगर करें।",
    sos_active: "SOS सक्रिय",
    geospatial_grid: "भू-स्थानिक ग्रिड",
    system_status: "सिस्टम स्थिति",
    sync_grid: "ग्रिड सिंक्रोनाइज़ हो रहा है...",
    dispatched_alerts: "अलर्ट भेजे गए।",
    target_center: "लक्ष्य केंद्र",
    calculating: "गणना हो रही है...",
    ai_medic: "AI मेडिक",
    emergency_guidance: "आपातकालीन मार्गदर्शन...",
    medic_welcome: "रास्तासाथी एआई मेडिक सक्रिय है। मैं आपके ग्रिड की निगरानी कर रहा हूँ।",
    initiating_protocol: "आपातकालीन प्रोटोकॉल शुरू: GPS डेटा प्राप्त कर रहा है...",
    gps_acquired: "📍 GPS निर्देशांक प्राप्त: ",
    sync_national: "राष्ट्रीय चिकित्सा ग्रिड के साथ सिंक्रोनाइज़ कर रहा है...",
    sos_success: "✅ SOS सफलतापूर्वक भेजा गया!",
    contacts_notified: "📲 आपातकालीन संपर्कों को व्हाट्सएप अलर्ट भेजे गए।",
    nearest_hospital: "🏥 निकटतम अस्पताल: ",
    nearest_police: "🚓 निकटतम पुलिस स्टेशन: ",
    eta: "⏳ आगमन का समय: ",
    no_hospitals: "⚠️ अलर्ट: SOS ट्रिगर हुआ, लेकिन आसपास कोई अस्पताल नहीं मिला।",
    ai_activated: "👨‍⚕️ AI मार्गदर्शन सक्रिय:",
    critical_error: "❌ गंभीर त्रुटि: ",
    geo_denied: "❌ स्थान अस्वीकृत: रास्तासाथी को अस्पतालों के लिए GPS की आवश्यकता है।",

    // Profile
    manage_grid: "अपनी पहचान और आपातकालीन प्रतिक्रिया ग्रिड प्रबंधित करें।",
    full_name: "पूरा नाम",
    lang_priority: "भाषा प्राथमिकता",
    emergency_contacts: "सुरक्षा नेटवर्क",
    recipients_sos: "आपके स्वचालित SOS अलर्ट प्राप्तकर्ता।",
    add_new: "संपर्क जोड़ें",
    save_grid: "सुरक्षा प्रोफ़ाइल अपडेट करें",
    no_contacts: "कोई आपातकालीन संपर्क नहीं मिला।",
    add_one_contact: "व्हाट्सएप अलर्ट सक्षम करने के लिए कम से कम एक संपर्क जोड़ें।",

    // Footer
    footer_tagline: "दुर्घटनाओं और जीवन रक्षक देखभाल के बीच की दूरी को पाटना।",
    hackathon_tag: "IIT मद्रास रोड सेफ्टी हैकाथॉन 2026",
    contact_email: "rastasaathi@gmail.com",
    contact_phone: "+91 944 192 1812",
    made_with: "बनाया गया है",
    by_team: "रास्तासाथी टीम द्वारा",
    official_protocol: "आधिकारिक आपातकालीन प्रोटोकॉल",
    golden_minute_title: "स्वर्णिम मिनट",
    golden_minute_sub: "आपातकाल में हर सेकंड मायने रखता है। रास्तासाथी को पूर्ण तकनीकी सटीकता के साथ 'स्वर्णिम घंटे' को भरने के लिए डिज़ाइन किया गया है।",
    human_impact: "मिशन क्रिटिकल",
    strategic_partnerships: "सामरिक नेटवर्क",
    emergency_liaison: "सत्यापित ट्रॉमा केंद्र",
    headquarters: "केंद्रीय नियंत्रण हब",
    direct_support: "इकोसिस्टम पार्टनर",
    direct_support_sub: "आपातकालीन प्रतिक्रिया को फिर से परिभाषित करने के लिए अपनी सुविधा को हमारे ग्रिड के साथ एकीकृत करें।",
    contact_us_now: "ग्रिड में शामिल हों",
    safety_first: "सुरक्षा प्रोटोकॉल",
    safety_assist_text: "रास्तासाथी एक सहायता उपकरण है। आपातकाल में हमेशा तुरंत 108/112 पर कॉल करें।",
    do_not: "क्या न करें",
    do: "क्या करें",
    do_not_move: "पीड़ित को तब तक न हिलाएं जब तक आग का खतरा न हो।",
    do_stay_line: "एम्बुलेंस आने तक एआई मेडिक के निर्देशों का पालन करें।",
    connect_now: "मिशन से जुड़ें",
    zero_delay: "शून्य विलंब",
    zero_delay_desc: "त्वरित स्वचालित प्रेषण प्रोटोकॉल।",
    scale: "अत्यधिक स्केलेबल",
    scale_desc: "शहर-व्यापी स्केल के लिए क्लाउड-नेटिव इंफ्रास्ट्रक्चर।",
    excellence: "चिकित्सा सटीकता",
    excellence_desc: "नैदानिक आपातकालीन डेटा पर प्रशिक्षित एआई मॉडल।",

    // Core Tech
    orch_feature1_title: "जियोस्पेशियल इंटेलिजेंस",
    orch_feature1_desc: "ट्रॉमा केंद्रों के साथ पीड़ितों का रीयल-टाइम मिलान।",
    orch_feature2_title: "एआई-संचालित ट्राइएज",
    orch_feature2_desc: "त्वरित, उच्च-सटीक चोट मूल्यांकन के साथ मानवीय देरी को कम करना।",
    orch_feature3_title: "विश्वसनीय सुरक्षा ग्रिड",
    orch_feature3_desc: "प्रतिक्रियादाताओं और अस्पतालों का एक सत्यापित नेटवर्क।",

    // Mission & About
    mission_page_title: "हमारा मिशन और विजन",
    mission_page_sub: "एआई के माध्यम से आपातकालीन प्रतिक्रिया के भविष्य को फिर से परिभाषित करना।",
    mission_v_title: "दृष्टिकोण",
    mission_v_desc: "एक ऐसी दुनिया जहाँ सड़क दुर्घटनाओं में कोई जान न जाए।",
    mission_m_title: "मिशन",
    mission_m_desc: "नागरिकों को रीयल-टाइम एआई ट्राइएज के साथ सशक्त बनाना।",
    mission_manifesto: "सुरक्षा घोषणापत्र",
    origin_tech: "हमारा टेक्नोलॉजी स्टैक",
    about_vision_title: "बुनियादी ढांचा",
    about_vision_desc: "एआई मॉडल और जियोस्पेशियल डेटाबेस का एक उच्च-प्रदर्शन पारिस्थितिकी तंत्र।",
    feature_ai_title: "इंटेलिजेंट ट्राइएज कोर",
    about_tech_desc: "हमारा आर्किटेक्चर रीयल-टाइम चिकित्सा मूल्यांकन प्रदान करने के लिए जेमिनी और क्लाउड का लाभ उठाता है।",
    feature_route_title: "सटीक रूटिंग",
    feature_route_desc: "पीड़ितों को विशेष ट्रॉमा केंद्रों के साथ मिलान करना।",
    response_gap_title: "प्रतिक्रिया अंतर को कम करना",
    response_gap_p1: "रास्तासाथी आपातकालीन प्रक्रिया को स्वचालित करता है, उन मिनटों को बचाता है जो जीवन बचाते हैं।",
    verified_protocols: "नैदानिक मानक",
    verified_protocols_desc: "सभी एआई प्रोटोकॉल अंतरराष्ट्रीय मानकों के अनुरूप हैं।",
    data_security: "एंटरप्राइज सुरक्षा",
    data_security_desc: "पीड़ित डेटा एंड-टू-एंड एन्क्रिप्शन के साथ सुरक्षित है।",
    citizen_first: "उपयोगकर्ता-केंद्रित डिज़ाइन",
    citizen_first_desc: "अत्यधिक तनाव में काम करने के लिए डिज़ाइन किया गया एक सहज इंटरफ़ेस।",
    latency: "प्रतिक्रिया समय",
    stats_hospitals: "चिकित्सा केंद्र",
    stats_responders: "सक्रिय प्रतिक्रियाकर्ता",
    project_stage: "विकास चरण",

    // Guide Usage
    guide_usage_title: "रास्तासाथी का उपयोग कैसे करें",
    guide_use_step1_title: "सुरक्षा प्रोफ़ाइल बनाएं",
    guide_use_step1_desc: "रजिस्टर करें और अपनी मेडिकल प्रोफ़ाइल पूरी करें। यह सुनिश्चित करता है कि बचावकर्मियों के पास आपातकालीन स्थिति में महत्वपूर्ण स्वास्थ्य डेटा हो।",
    guide_use_step2_title: "सुरक्षा नेटवर्क बनाएं",
    guide_use_step2_desc: "अपने आपातकालीन संपर्क जोड़ें। यदि आप SOS ट्रिगर करते हैं तो उन्हें आपके लाइव स्थान के साथ स्वचालित व्हाट्सएप अलर्ट प्राप्त होंगे।",
    guide_use_step3_title: "व्हाट्सएप अलर्ट सक्रिय करें",
    guide_use_step3_desc: "हमारे स्वचालित अलर्ट ग्रिड से जुड़ें। रीयल-टाइम मैसेजिंग सक्षम करने के लिए हमारे नंबर पर 'join soft-peace' भेजें।",
    guide_use_step4_title: "SOS प्रोटोकॉल ट्रिगर करें",
    guide_use_step4_desc: "आपातकालीन स्थिति में, SOS बटन दबाएं। हमारा इंजन तुरंत आपको सर्वोत्तम उपलब्ध ट्रॉमा सेंटर से मिलाता है।",
    guide_use_step5_title: "AI मेडिक से परामर्श करें",
    guide_use_step5_desc: "तत्काल प्राथमिक चिकित्सा मार्गदर्शन प्राप्त करने के लिए हमारे AI ट्राइएज का उपयोग करें। मदद आने तक पीड़ित को स्थिर करें।",
    guide_use_step6_title: "रेस्क्यू मैप का पालन करें",
    guide_use_step6_desc: "रीयल-टाइम में प्रेषण को ट्रैक करें। निकटतम सत्यापित चिकित्सा सुविधा के लिए अनुकूलित मार्गों का पालन करें।",
    twilio_command: "Join soft-peace",
    severity_label: "गंभीरता",
    first_aid_label: "प्राथमिक चिकित्सा निर्देश",
    avoid_label: "क्या न करें",
    call_108: "108 आपातकालीन कॉल करें",
    select_emergency: "आपातकालीन स्थिति चुनें",
    describe_situation: "स्थिति का वर्णन करें...",
    critical_severity: "गंभीर",
    high_severity: "उच्च",
    medium_severity: "मध्यम",
    low_severity: "कम",
    protocol_for: "प्रोटोकॉल के लिए",
    medic_fallback_msg: "मैं समझता हूँ कि यह एक आपात स्थिति है। कृपया सूची में से चुनें या 'रक्तस्राव' या 'जलन' जैसे कीवर्ड टाइप करें। हमेशा तुरंत 108 पर कॉल करें।",
    
    // Road Safety Categories
    general_tips: "सामान्य सुझाव",
    pedestrian_safety: "पैदल यात्रियों के लिए",
    driver_safety: "वाहन चालकों के लिए",
    child_safety: "बच्चों के लिए",
    parent_safety: "अभिभावकों के लिए"
  },
  te: {
    // Navigation
    home: "హోమ్",
    about: "మా గురించి",
    guide: "గైడ్",
    contact: "సంప్రదించండి",
    dashboard: "డాష్‌బోర్డ్",
    login: "లాగిన్",
    logout: "లాగౌట్",
    profile: "ప్రొఫైల్",
    road_safety: "భద్రతా మార్గదర్శకాలు",
    vision_mission: "విజన్ & మిషన్",
    language_label: "భాష",
    navigation: "నావిగేషన్",

    // Home Page
    hero_title: "ప్రతి సెకను విలువైనప్పుడు, RastaSaathi స్పందిస్తుంది.",
    hero_sub: "ప్రమాదానికి మరియు ప్రాణరక్షక సంరక్షణకు మధ్య ఉన్న అంతరాన్ని పూడ్చడానికి రాస్తాసాథీ ఏఐని ఉపయోగిస్తుంది.",
    view_guide: "మార్గదర్శిని చూడండి",
    vision: "దృష్టి",
    national_initiative: "జాతీయ రహదారి భద్రతా చొరవ",
    precision_eng: "ఖచ్చితమైన ఇంజనీరింగ్",
    impact_title: "ప్రతి పౌరుడిని శక్తివంతం చేయడం",
    impact_sub: "మా సాంకేతికత అత్యవసర సమయాల్లో ఆలస్యం లేకుండా స్పందించడానికి ఏఐ ట్రైయేజ్‌ని ఉపయోగిస్తుంది.",
    results_title: "ఫలితాల కోసం రూపొందించబడింది.",
    journey_title: "భద్రతా ప్రయాణం",
    journey_sub: "సాంకేతికత మరియు వైద్య నైపుణ్యం యొక్క ఖచ్చితమైన సమన్వయం.",
    step1_title: "SOS ట్రిగ్గర్ చేయండి",
    step1_desc: "ప్రోటోకాల్‌ను ప్రారంభించడానికి ఎమర్జెన్సీ బటన్‌ను నొక్కండి. మేము ఖచ్చితమైన GPS డేటాను సేకరిస్తాము.",
    step2_title: "AI అంచనా",
    step2_desc: "మా మెడికల్ ఇంజిన్ గాయం తీవ్రతను మరియు ఆసుపత్రి అవసరాలను గుర్తిస్తుంది.",
    step3_title: "రెస్క్యూ ప్రారంభం",
    step3_desc: "సమీప ఆసుపత్రికి అలర్ట్ వెళ్తుంది మరియు నావిగేషన్ వెంటనే ప్రారంభమవుతుంది.",
    join_national_mission: "జాతీయ మిషన్‌లో చేరండి",
    become_responder: "రెస్పాండర్ అవ్వండి",

    // Dashboard
    secure_terminal: "సురక్షిత అత్యవసర టెర్మినల్",
    ready_dispatch: "పంపడానికి సిద్ధంగా ఉంది.",
    trigger_sub: "తక్షణ అలర్ట్‌ల కోసం SOS ట్రిగ్గర్ చేయండి.",
    sos_active: "SOS యాక్టివ్",
    geospatial_grid: "జియోస్పేషియల్ గ్రిడ్",
    system_status: "సిస్టమ్ స్థితి",
    sync_grid: "గ్రిడ్ సింక్ అవుతోంది...",
    dispatched_alerts: "అలర్ట్‌లు పంపబడ్డాయి.",
    target_center: "టార్గెట్ సెంటర్",
    calculating: "లెక్కిస్తోంది...",
    ai_medic: "AI మెడిక్",
    emergency_guidance: "అత్యవసర మార్గదర్శకత్వం...",
    medic_welcome: "రాస్తాసాథీ AI మెడిక్ యాక్టివ్‌గా ఉంది. నేను మీ గ్రిడ్‌ను పర్యవేక్షిస్తున్నాను.",
    initiating_protocol: "అత్యవసర ప్రోటోకాల్ ప్రారంభం: GPS డేటాను పొందుతోంది...",
    gps_acquired: "📍 GPS కోఆర్డినేట్స్ పొందబడ్డాయి: ",
    sync_national: "జాతీయ వైద్య గ్రిడ్‌తో సింక్ అవుతోంది...",
    sos_success: "✅ SOS విజయవంతంగా పంపబడింది!",
    contacts_notified: "📲 అత్యవసర కాంటాక్ట్‌లకు వాట్సాప్ అలర్ట్‌లు పంపబడ్డాయి.",
    nearest_hospital: "🏥 సమీప ఆసుపత్రి: ",
    nearest_police: "🚓 సమీప పోలీస్ స్టేషన్: ",
    eta: "⏳ చేరుకునే సమయం: ",
    no_hospitals: "⚠️ అలర్ట్: SOS ట్రిగ్గర్ అయ్యింది, కానీ సమీపంలో ఆసుపత్రులు లేవు.",
    ai_activated: "👨‍⚕️ AI మార్గదర్శకత్వం యాక్టివ్:",
    critical_error: "❌ తీవ్రమైన లోపం: ",
    geo_denied: "❌ లొకేషన్ నిరాకరించబడింది: రాస్తాసాథీకి GPS అవసరం.",

    // Profile
    manage_grid: "మీ గుర్తింపు మరియు అత్యవసర ప్రతిస్పందన గ్రిడ్‌ను నిర్వహించండి.",
    full_name: "పూర్తి పేరు",
    lang_priority: "భాషా ప్రాధాన్యత",
    emergency_contacts: "భద్రతా నెట్‌వర్క్",
    recipients_sos: "మీ ఆటోమేటెడ్ SOS అలర్ట్ గ్రహీతలు.",
    add_new: "కాంటాక్ట్ యాడ్ చేయండి",
    save_grid: "సేఫ్టీ ప్రొఫైల్ అప్‌డేట్ చేయండి",
    no_contacts: "మీ నెట్‌వర్క్‌లో కాంటాక్ట్‌లు లేవు.",
    add_one_contact: "వాట్సాప్ అలర్ట్‌లను ప్రారంభించడానికి కనీసం ఒక కాంటాక్ట్‌ను యాడ్ చేయండి.",

    // Footer
    footer_tagline: "ప్రతి సెకను విలువైనప్పుడు, RastaSaathi స్పందిస్తుంది.",
    hackathon_tag: "IIT మద్రాస్ రోడ్ సేఫ్టీ హ్యాకథాన్ 2026",
    contact_email: "rastasaathi@gmail.com",
    contact_phone: "+91 944 192 1812",
    made_with: "తయారు చేయబడింది",
    by_team: "రాస్తాసాథీ టీమ్ ద్వారా",
    official_protocol: "అధికారిక అత్యవసర ప్రోటోకాల్",
    golden_minute_title: "గోల్డెన్ మినిట్",
    golden_minute_sub: "అత్యవసర సమయంలో ప్రతి సెకను ముఖ్యం. రాస్తాసాథీ ఖచ్చితమైన సాంకేతికతతో రూపొందించబడింది.",
    human_impact: "మానవ ప్రభావం",
    strategic_partnerships: "వ్యూహాత్మక భాగస్వామ్యాలు",
    emergency_liaison: "ఎమర్జెన్సీ లైజన్",
    headquarters: "ప్రధాన కార్యాలయం",
    direct_support: "ప్రత్యక్ష మద్దతు",
    direct_support_sub: "మీరు వైద్య నిపుణులైతే, దయచేసి ఈమెయిల్ ద్వారా సంప్రదించండి.",
    contact_us_now: "సంప్రదించండి",
    safety_first: "భద్రతా ప్రోటోకాల్",
    safety_assist_text: "రాస్తాసాథీ ఒక సహాయక సాధనం. అత్యవసర సమయంలో ఎల్లప్పుడూ 108/112 కు కాల్ చేయండి.",
    do_not: "చేయకూడనివి",
    do: "చేయవలసినవి",
    do_not_move: "ప్రమాదం లేకపోతే గాయపడిన వ్యక్తిని కదిలించవద్దు.",
    do_stay_line: "సహాయం వచ్చే వరకు AI మెడిక్ సూచనలను పాటించండి.",
    connect_now: "మిషన్‌లో చేరండి",
    zero_delay: "జీరో డిలే",
    zero_delay_desc: "తక్షణ ఆటోమేటెడ్ డిస్పాచ్ ప్రోటోకాల్స్.",
    scale: "హైపర్-స్కేలబుల్",
    scale_desc: "నగర వ్యాప్తంగా స్కేల్ కోసం క్లౌడ్-నేటివ్ ఇన్ఫ్రాస్ట్రక్చర్.",
    excellence: "వైద్య ఖచ్చితత్వం",
    excellence_desc: "వైద్య డేటాపై శిక్షణ పొందిన AI మోడల్స్.",
    severity_label: "తీవ్రత",
    first_aid_label: "ప్రథమ చికిత్స సూచనలు",
    avoid_label: "ఏమి చేయకూడదు",
    call_108: "108 అత్యవసర కాల్",
    select_emergency: "అత్యవసర రకాన్ని ఎంచుకోండి",
    describe_situation: "పరిస్థితిని వివరించండి...",
    critical_severity: "తీవ్రమైనది",
    high_severity: "ఎక్కువ",
    medium_severity: "మధ్యస్థం",
    low_severity: "తక్కువ"
  },
  ta: {
    // Navigation
    home: "முகப்பு",
    about: "எங்களைப் பற்றி",
    guide: "வழிகாட்டி",
    contact: "தொடர்பு",
    dashboard: "டாஷ்போர்டு",
    login: "உள்நுழைவு",
    logout: "வெளியேறுதல்",
    profile: "சுயவிவரம்",
    road_safety: "பாதுகாப்பு வழிகாட்டுதல்கள்",
    vision_mission: "பார்வையும் நோக்கமும்",
    language_label: "மொழி",
    navigation: "வழிசெலுத்தல்",

    // Home Page
    hero_title: "ஒவ்வொரு நொடியும் முக்கியம் எனும்போது, RastaSaathi பதிலளிக்கிறது.",
    hero_sub: "விபத்துக்கும் உயிர்காக்கும் சிகிச்சைக்கும் இடையிலான இடைவெளியைக் குறைக்க ராஸ்தாசாத்தி உதவுகிறது.",
    view_guide: "வழிகாட்டியைப் பார்க்கவும்",
    vision: "நோக்கம்",
    national_initiative: "தேசிய சாலை பாதுகாப்பு முயற்சி",
    precision_eng: "துல்லியமான பொறியியல்",
    impact_title: "ஒவ்வொரு குடிமகனையும் மேம்படுத்துதல்",
    impact_sub: "எங்கள் தொழில்நுட்பம் அவசர காலங்களில் விரைவாக செயல்பட AI ஐப் பயன்படுத்துகிறது.",
    results_title: "முடிவுகளுக்காக வடிவமைக்கப்பட்டது.",
    journey_title: "பாதுகாப்பு பயணம்",
    journey_sub: "தொழில்நுட்பம் మరియు వైద్య నిపుణత్వத்தின் துல்லியமான ஒருங்கிணைப்பு.",
    step1_title: "SOS ஐத் தொடங்கவும்",
    step1_desc: "அவசர பொத்தானை அழுத்தவும். நாங்கள் துல்லியமான GPS தரவைப் பிடிக்கிறோம்.",
    step2_title: "AI மதிப்பீடு",
    step2_desc: "எங்கள் மருத்துவ இயந்திரம் காயத்தின் தீவிரத்தை அடையாளம் காட்டுகிறது.",
    step3_title: "மீட்பு ஆரம்பம்",
    step3_desc: "அருகிலுள்ள மருத்துவமனைக்கு எச்சரிக்கை அனுப்பப்பட்டு வழிகாட்டுதல் தொடங்குகிறது.",
    join_national_mission: "தேசிய பணியில் இணையுங்கள்",
    become_responder: "பதிலளிப்பவராகுங்கள்",

    // Dashboard
    secure_terminal: "பாதுகாப்பான அவசர முனையம்",
    ready_dispatch: "அனுப்பத் தயார்.",
    trigger_sub: "உடனடி எச்சரிக்கைகளுக்கு SOS ஐத் தொடங்கவும்.",
    sos_active: "SOS செயலில் உள்ளது",
    geospatial_grid: "புவிசார் கட்டம்",
    system_status: "அமைப்பின் நிலை",
    sync_grid: "ஒத்திசைக்கப்படுகிறது...",
    dispatched_alerts: "எச்சரிக்கைகள் அனுப்பப்பட்டன.",
    target_center: "இலக்கு மையம்",
    calculating: "கணக்கிடப்படுகிறது...",
    ai_medic: "AI மருத்துவர்",
    emergency_guidance: "அவசர வழிகாட்டுதல்...",
    medic_welcome: "ராஸ்தாசாத்தி AI மருத்துவர் செயலில் உள்ளார்.",
    initiating_protocol: "அவசர நெறிமுறை ஆரம்பம்: GPS தரவைப் பெறுகிறது...",
    gps_acquired: "📍 GPS தரவு பெறப்பட்டது: ",
    sync_national: "தேசிய மருத்துவ கட்டத்துடன் ஒத்திசைக்கப்படுகிறது...",
    sos_success: "✅ SOS வெற்றிகரமாக அனுப்பப்பட்டது!",
    contacts_notified: "📲 அவசர தொடர்புகளுக்கு வாட்ஸ்அப் எச்சரிக்கைகள் அனுப்பப்பட்டன.",
    nearest_hospital: "🏥 அருகிலுள்ள மருத்துவமனை: ",
    nearest_police: "🚓 அருகிலுள்ள காவல் நிலையம்: ",
    eta: "⏳ வருகை நேரம்: ",
    no_hospitals: "⚠️ எச்சரிக்கை: SOS தொடங்கப்பட்டது, ஆனால் அருகில் மருத்துவமனைகள் இல்லை.",
    ai_activated: "👨‍⚕️ AI வழிகாட்டுதல் செயலில் உள்ளது:",
    critical_error: "❌ பிழை: ",
    geo_denied: "❌ இருப்பிடம் மறுக்கப்பட்டது: GPS தேவை.",

    // Profile
    manage_grid: "உங்கள் அடையாளம் மற்றும் அவசர கால நடவடிக்கைகளை నిర్వహించండి.",
    full_name: "முழு பெயர்",
    lang_priority: "மொழி விருப்பம்",
    emergency_contacts: "பாதுகாப்பு நெட்வொர்க்",
    recipients_sos: "உங்கள் தானியங்கி SOS எச்சரிக்கை பெறுநர்கள்.",
    add_new: "தொடர்பைச் சேர்க்கவும்",
    save_grid: "சுயவிவரத்தைப் புதுப்பிக்கவும்",
    no_contacts: "தொடர்புகள் எதுவும் இல்லை.",
    add_one_contact: "வாட்ஸ்அப் எச்சரிக்கைகளைச் செயல்படுத்த ஒரு தொடர்பையாவது சேர்க்கவும்.",
    severity_label: "தீவிரம்",
    first_aid_label: "முதலுதவி வழிமுறைகள்",
    avoid_label: "தவிர்க்க வேண்டியவை",
    call_108: "108 அவசர அழைப்பு",
    select_emergency: "அவசர வகையைத் தேர்ந்தெடுக்கவும்",
    describe_situation: "சூழ்நிலையை விளக்கவும்...",
    critical_severity: "மிகவும் தீவிரம்",
    high_severity: "அதிகம்",
    medium_severity: "மிதமான",
    low_severity: "குறைவு"
  },
  ur: {
    home: "ہوم",
    about: "ہمارے بارے میں",
    guide: "گائیڈ",
    contact: "رابطہ کریں",
    dashboard: "ڈیش بورڈ",
    login: "لاگ ان",
    logout: "لاگ آؤٹ",
    profile: "پروفائل",
    road_safety: "حفاظتی رہنما",
    vision_mission: "وژن اور مشن",
    language_label: "زبان",
    navigation: "نیویگیشن",
    hero_title: "جب ہر سیکنڈ اہم ہوتا ہے، RastaSaathi جواب دیتا ہے۔",
    hero_sub: "راستہ ساتھی حادثے اور جان بچانے والی دیکھ بھال کے درمیان فرق کو ختم کرنے کے لیے AI اور ریئل ٹائم الرٹس کا استعمال کرتا ہے۔",
    view_guide: "گائیڈ دیکھیں",
    vision: "ہمارا وژن",
    national_initiative: "نیشنل روڈ سیفٹی انیشیٹو",
    precision_eng: "پریسجن انجینئرنگ",
    impact_title: "ہر شہری کو بااختیار بنانا",
    impact_sub: "ہماری ٹیکنالوجی صفر لیٹنسی ہنگامی ردعمل کو یقینی بنانے کے لیے جغرافیائی انڈیکسنگ کے ساتھ AI ٹرائیج کو یکجا کرتی ہے۔",
    results_title: "نتائج کے لیے انجینئرڈ۔",
    journey_title: "حفاظت کا سفر",
    step1_title: "SOS ٹرگر کریں",
    step1_desc: "ہنگامی پروٹوکول شروع کرنے کے لیے بٹن دبائیں۔ ہم درست GPS ڈیٹا حاصل کرتے ہیں۔",
    step2_title: "AI تشخیص",
    step2_desc: "ہمارا میڈیکل انجن چوٹ کی شدت اور ہسپتال کی ضروریات کی شناخت کرتا ہے۔",
    step3_title: "بچاؤ کا آغاز",
    step3_desc: "قریبی ہسپتال کو الرٹ کیا جاتا ہے اور نیویگیشن فوری طور پر شروع ہو جاتی ہے۔",
    severity_label: "شدت",
    first_aid_label: "ابتدائی طبی امداد کی ہدایات",
    avoid_label: "کیا نہ کریں",
    call_108: "108 پر ہنگامی کال کریں",
    select_emergency: "ہنگامی قسم منتخب کریں",
    describe_situation: "صورتحال بیان کریں...",
    critical_severity: "سنگین",
    high_severity: "زیادہ",
    medium_severity: "درمیانہ",
    low_severity: "کم",
    twilio_command: "Join soft-peace"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en');

  const t = (key) => {
    // Robust translation logic with direct name fallbacks
    const translation = TRANSLATIONS[lang]?.[key] || TRANSLATIONS['en'][key];
    
    if (translation) return translation;

    // Direct name fallbacks for common label leaks
    const fallbacks = {
      severity_label: "Severity",
      first_aid_label: "First Aid Instructions",
      avoid_label: "What to Avoid",
      describe_situation: "Describe the situation..."
    };

    return fallbacks[key] || key;
  };

  const setLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem('raasta_lang', newLang);
  };

  React.useEffect(() => {
    const saved = localStorage.getItem('raasta_lang');
    if (saved && TRANSLATIONS[saved]) {
      setLang(saved);
    }
  }, []);

  return (
    <LanguageContext.Provider value={{ lang, setLang: setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
