const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Service to generate a professional Accident Report PDF
 */
async function generateAccidentReport(incident, victimUser, routingData) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const filename = `Report_${incident._id}.pdf`;
      const reportsDir = path.join(__dirname, '../../public/reports');
      
      if (!fs.existsSync(reportsDir)) {
        fs.mkdirSync(reportsDir, { recursive: true });
      }
      
      const filePath = path.join(reportsDir, filename);
      const stream = fs.createWriteStream(filePath);
      
      doc.pipe(stream);

      // --- Header ---
      doc.fontSize(25).fillColor('#ef4444').text('RastaSaathi', { align: 'left' });
      doc.fontSize(10).fillColor('#64748b').text('Official Emergency Incident Report', { align: 'left' });
      doc.moveDown();
      doc.strokeColor('#e2e8f0').moveTo(50, 100).lineTo(550, 100).stroke();
      doc.moveDown();

      // --- Incident Summary ---
      doc.fontSize(16).fillColor('#1e293b').text('INCIDENT SUMMARY', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor('#334155');
      doc.text(`Incident ID: ${incident._id}`);
      doc.text(`Timestamp: ${new Date(incident.createdAt).toLocaleString()}`);
      doc.text(`Location: ${incident.location.coordinates[1]}, ${incident.location.coordinates[0]}`);
      doc.text(`Injury Type: ${incident.injuryType || 'Not specified'}`);
      doc.text(`Vehicle Involved: ${incident.vehicleType || 'None'}`);
      doc.moveDown();

      // --- Victim Details ---
      if (victimUser) {
        doc.fontSize(16).fillColor('#1e293b').text('USER PROFILE', { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(11).fillColor('#334155');
        doc.text(`Name: ${victimUser.name}`);
        doc.text(`Phone: ${victimUser.phone}`);
        doc.text(`Emergency Contacts: ${victimUser.emergencyContacts?.map(c => `${c.name} (${c.phone})`).join(', ') || 'None'}`);
        doc.moveDown();
      }

      // --- Response Coordination ---
      doc.fontSize(16).fillColor('#1e293b').text('RESPONSE COORDINATION', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor('#334155');
      
      if (routingData.hospitalSelection?.[0]) {
        const h = routingData.hospitalSelection[0].hospital;
        doc.text(`Primary Hospital: ${h.name}`);
        doc.text(`Hospital Address: ${h.address}`);
      }

      if (routingData.policeSelection?.[0]) {
        const p = routingData.policeSelection[0];
        doc.text(`Nearest Police Station: ${p.name}`);
        doc.text(`Police Address: ${p.address}`);
      }
      
      doc.moveDown();

      // --- Footer ---
      doc.fontSize(10).fillColor('#94a3b8').text('This report was automatically generated by the RastaSaathi AI Routing Engine.', { align: 'center', baseline: 'bottom' });

      doc.end();

      stream.on('finish', () => {
        resolve({ filename, filePath, publicUrl: `/reports/${filename}` });
      });

    } catch (error) {
      reject(error);
    }
  });
}

module.exports = { generateAccidentReport };
